services:
  python-run:
    entrypoint:
      - pipenv
      - run
      - python
      - main.py
    environment:  
      - PYTHONPATH
    image: python-image
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  python-dev:
    entrypoint: bash
    environment:  
      - PYTHONPATH
    image: python-image
    volumes:
      - type: bind
        source: .
        target: /usr/src/app